scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080

  - job_name: falco
    scrape_interval: 15s
    static_configs:
      - targets:
          - falco:8765
          

  - job_name: node
    scrape_interval: 5s
    static_configs:
      - targets: ['node:9100']