FROM python:3.13-alpine


# Install required system dependencies
RUN apk add --no-cache g++ gcc libffi-dev musl-dev python3-dev cmake \
    linux-headers libstdc++ bash curl

WORKDIR /code

COPY ./backend/requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./backend/ /code/

# COPY ./backend/receive.py /code/

EXPOSE 8000
